### ISSUE TITLE
zen.coderdojo.com not working with Firefox

### ISSUE THREAD

**Issue by sandrobonazzola** [CoderDojo/cp-zen-platform#1015]
When opening zen.coderdojo.com firefox log errors in console and doesn't display the website:

Content Security Policy: directive “frame-src” is deprecated. use “child-src” instead.
Content Security Policy: directive “reflected-xss” is not supported. directive and associated values will be ignored

Error: $scope.model.map is undefined
cdDojosMapCtrl/$scope.loadMap@https://zen.coderdojo.com/dist/app.js:6616:7
cdDojosMapCtrl@https://zen.coderdojo.com/dist/app.js:6620:3
s@https://zen.coderdojo.com/dist/dependencies.js:7:6426
$t/this.$get</<@https://zen.coderdojo.com/dist/dependencies.js:8:337
C/<.compile/<@https://zen.coderdojo.com/dist/dependencies.js:30:24385
G/<@https://zen.coderdojo.com/dist/dependencies.js:6:23204
me@https://zen.coderdojo.com/dist/dependencies.js:7:27486
f@https://zen.coderdojo.com/dist/dependencies.js:7:19934
a@https://zen.coderdojo.com/dist/dependencies.js:7:15892
F/<@https://zen.coderdojo.com/dist/dependencies.js:7:15423
K/<@https://zen.coderdojo.com/dist/dependencies.js:7:18027
p@https://zen.coderdojo.com/dist/dependencies.js:30:23584
k/p.compile/</<@https://zen.coderdojo.com/dist/dependencies.js:30:24004
kn/this.$get</h.prototype.$broadcast@https://zen.coderdojo.com/dist/dependencies.js:8:31117
w/k.transitionTo/k.transition<@https://zen.coderdojo.com/dist/dependencies.js:30:19304
a@https://zen.coderdojo.com/dist/dependencies.js:8:22017
s/<@https://zen.coderdojo.com/dist/dependencies.js:8:22189
kn/this.$get</h.prototype.$eval@https://zen.coderdojo.com/dist/dependencies.js:8:29732
kn/this.$get</h.prototype.$digest@https://zen.coderdojo.com/dist/dependencies.js:8:28214
kn/this.$get</h.prototype.$apply@https://zen.coderdojo.com/dist/dependencies.js:8:30017
l@https://zen.coderdojo.com/dist/dependencies.js:8:4444
$@https://zen.coderdojo.com/dist/dependencies.js:8:6349
Lt/</x.onload@https://zen.coderdojo.com/dist/dependencies.js:8:6892
 <div ui-view="" class="ng-scope" data-ng-animate="1">dependencies.js:8:14735

Error: this.map_ is undefined
MarkerClusterer@https://zen.coderdojo.com/dist/dependencies.js:1:1894
addMarkersToMap/<@https://zen.coderdojo.com/dist/app.js:6784:25
_n/$@https://zen.coderdojo.com/dist/dependencies.js:8:24382
addMarkersToMap@https://zen.coderdojo.com/dist/app.js:6768:12
cdDojosMapCtrl/$scope.loadMap/<@https://zen.coderdojo.com/dist/app.js:6590:7
.post/<@https://zen.coderdojo.com/dist/app.js:185:9
a@https://zen.coderdojo.com/dist/dependencies.js:8:22017
s/<@https://zen.coderdojo.com/dist/dependencies.js:8:22189
kn/this.$get</h.prototype.$eval@https://zen.coderdojo.com/dist/dependencies.js:8:29732
kn/this.$get</h.prototype.$digest@https://zen.coderdojo.com/dist/dependencies.js:8:28214
kn/this.$get</h.prototype.$apply@https://zen.coderdojo.com/dist/dependencies.js:8:30017
l@https://zen.coderdojo.com/dist/dependencies.js:8:4444
$@https://zen.coderdojo.com/dist/dependencies.js:8:6349
Lt/</x.onload@https://zen.coderdojo.com/dist/dependencies.js:8:6892

"Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"util.js:208:33

Use of getPreventDefault() is deprecated. Use defaultPrevented instead.       3847550948.js:91:44

**Comment by DanielBrierton** [comment]
Hi Sandro,

What version of Firefox are you using, and on what OS? I have the latest (49.0.1) on macOS, and have no issue loading Zen on it.

Daniel

**Comment by Wardormeur** [comment]
Same for me on firefox 48, no issue especifically apart from the CSP alerts

**Comment by sandrobonazzola** [comment]
I've issues with it both on Windows 10 and Fedora 24 with Firefox 49.0.1

**Comment by sandrobonazzola** [comment]
Works fine with google chrome btw.

**Comment by Wardormeur** [comment]
Updated to FF 49, fedora 24 too. No issue tho. Could it be a plugin you have in both FF ?

**Comment by sandrobonazzola** [comment]
Looks like it's not a plugin but an extension: https://www.eff.org/privacybadger , sorry for the noise, closing the issue.
