### ISSUE TITLE
https://coderdojo.com/start-a-dojo/ TypeError: el is null

### ISSUE THREAD

**Issue by sandrobonazzola** [CoderDojo/cp-zen-platform#1016]
Loading https://coderdojo.com/start-a-dojo/ javascript console logs:
TypeError: el is null start-a-dojo:507

**Comment by sandrobonazzola** [comment]
In google chrome the above mentioned error is:
(index):507 Uncaught TypeError: Cannot read property 'addEventListener' of null(anonymous function) @ (index):507
util.js:208 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

**Comment by Wardormeur** [comment]
It's the map, it needs to be reworked anyway ;)

**Comment by sandrobonazzola** [comment]
@Wardormeur is the map also about the addEventListener?

**Comment by Wardormeur** [comment]
Looks like, yes :)
```google.maps.event.addDomListener(window, 'load', function() {
  el = document.getElementById("location");
  if (el.addEventListener) {
    el.addEventListener('change', function() ```

**Comment by sandrobonazzola** [comment]
@Wardormeur :+1:

**Comment by Wardormeur** [comment]
Closing, the page has been reworked from scratch
