### ISSUE TITLE
Users unable to join or leave a dojo

### ISSUE THREAD

**Issue by IzzySmillie** [CoderDojo/cp-zen-platform#1464]
- Users appear unable to join a Dojo or leave a Dojo. This is an issue for safeguarding.
- [Story](https://github.com/RaspberryPiFoundation/digital-foundation/issues/334)
- [Monday thread](https://raspberrypi.monday.com/boards/1236004929/pulses/2599057936)

**Info from thread**

Test account : [Mary Jane Smith](https://zen.coderdojo.com/profile/4462f768-b908-42a3-8a70-0dd5e26ee22a) ([testchampion@coderdojo.com](mailto:testchampion@coderdojo.com))

1. Requested to join Docklands Dojo , but not appearing in the [User Request (pending) list in Docklands](https://zen.coderdojo.com/dashboard/my-dojos/358784b6-79e2-4e43-80a4-792da79f5418/users/pending) (this takes a long time to load also). This Dojo is currently inactive, but I have tested it in both an active and inactive status

![Screenshot 2022-05-12 at 12 17 49](https://user-images.githubusercontent.com/14238047/168062881-17b6e5fc-b5c9-4feb-a15a-88471beaf6d2.png)

2. Is part of the [Test Dojo](https://zen.coderdojo.com/dojos/nc/nang/this-is-a-test-club-for-dev-and-example-purposes) as a volunteer, but there is no option for them to leave the Dojo on their 'My Dojos' page

![Screenshot 2022-05-12 at 12 16 23](https://user-images.githubusercontent.com/14238047/168062618-6e68fab8-ef3f-4e82-bb2d-6332b574f5db.png)

** Side note: If you click on `Active users` from the [User requests page](https://zen.coderdojo.com/dashboard/my-dojos/358784b6-79e2-4e43-80a4-792da79f5418/users/pending) it 404s https://zen.coderdojo.com/404

** Check with Mel or Izzy for login details for the testchampion (also on slack)

**Comment by IzzySmillie** [comment]
Ability to leave appears sometimes:

![Screenshot 2022-05-16 at 09 17 54](https://user-images.githubusercontent.com/14238047/168549565-84a68457-fec9-4dc7-b8dc-9ab19c8029a2.png)

**Comment by IzzySmillie** [comment]
### Continued testing: 

Checking a user with role: volunteer has the ability to leave a dojo -> Appears they do.
1. I made the Dojo as `John`. Then logged out and back in as `Jane`. 
2. I then joined the Dojo and changed Jane to be a volunteer
![Screenshot 2022-05-26 at 11 02 09](https://user-images.githubusercontent.com/14238047/170466513-f1dd52cc-cb79-44b7-9bfd-d07a5e3a0e4f.png)
3. Checking the dojo on `My Dojos` the `Leave Dojo` button does appear
![Screenshot 2022-05-26 at 11 02 17](https://user-images.githubusercontent.com/14238047/170466654-811b85c2-7e6d-4752-907d-ecbc929232af.png)
4. I then pressed the button to check functionality works
![Screenshot 2022-05-26 at 11 02 23](https://user-images.githubusercontent.com/14238047/170466759-81ec4263-61bd-4c6c-9a0c-220639614534.png)
5. Ta da! No longer part of the dojo
![Screenshot 2022-05-26 at 11 02 29](https://user-images.githubusercontent.com/14238047/170466792-c079f9c7-1e8c-4f14-9e02-676ad83474a6.png)
![Screenshot 2022-05-26 at 11 06 40](https://user-images.githubusercontent.com/14238047/170466863-0ca0ffb2-b90c-44ff-8d22-a69a7fb1883e.png)

**Comment by IzzySmillie** [comment]
Added `Blocked` label as looks fixed on our end. Waiting on video showing it not working from Helen

**Comment by MFarringtonRPF** [comment]
Closed issue as Helen was unable to replicate on production, therefore we are unable to replicate the bugs on either environment.
