### ISSUE TITLE
Twitter handle

### ISSUE THREAD

**Issue by Aryess** [CoderDojo/cp-zen-platform#678]
On the profile page, I probably shouldn't have to fill "twitter.com/myhandle" but just "myhandle".

**Comment by tangentfairy** [comment]
Hi @Aryess welcome! Can you create issues on this repo please? https://github.com/CoderDojo/community-platform/issues  

We did originally have the Twitter handle that way but users found it confusing...

**Comment by Aryess** [comment]
Wups, sorry about that
