### ISSUE TITLE
Map marker information is inconsistent. 

### ISSUE THREAD

**Issue by adhorrig** [CoderDojo/cp-zen-platform#786]
If you visit: https://zen.coderdojo.com/?_ga=1.25025658.1378620176.1449099463

This is what you will see ( once you select a single dojo):
![ojytro1](https://cloud.githubusercontent.com/assets/7798970/12075460/4564ab84-b179-11e5-945f-6b736461c95a.png)

However, on the home page: https://coderdojo.com/
When you click onto a single dojo map marker, you aren't greeted with any additional information. 
With the first link, you get the name of the area that the Dojo is located in a popup once you click on a map marker.

One map shows additional information when a Dojo marker is clicked, while another map doesn't show any additional information. 

Maybe more information could also be put into the marker popups? (Contact number, email etc)

**Comment by kennanseno** [comment]
Checked the dojo listing and the name of the dojo is actually 'Dublin 15'. Also the dojo name in the popup directs you to that dojo's zen page where all the necessary information can be seen.

<img width="774" alt="screen shot 2016-01-02 at 22 48 38" src="https://cloud.githubusercontent.com/assets/7852866/12076444/76792aae-b1a3-11e5-8e47-83af86ef46e9.png">

**Comment by adhorrig** [comment]
Yes that makes sense. 

I suppose with one map, the name of the Dojo is displayed in a popup from the marker and with a different map, the name of the Dojo is displayed beneath the Map itself. 

Thanks, will do from now on!

**Comment by tangentfairy** [comment]
In the future, reported issues go into the community-platform repository,
that is where we keep track of issues.

On Saturday, January 2, 2016, Adam Horrigan <notifications@github.com>
wrote:

> Closed #786 <https://github.com/CoderDojo/cp-zen-platform/issues/786>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/cp-zen-platform/issues/786#event-504064290>.
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.
