### ISSUE TITLE
dojo users list not rendered

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/cp-zen-platform#851]
User role: Champion
URL: https://zen.coderdojo.com/dashboard/my-dojos/8308d14d-dda8-49a4-b217-6d07e9f88e2d/users

Details: 
dojo users list page is not rendering users data, only header

Pastebin:
http://pastebin.com/J87V8neV

How reproduce it:
1) login zen platform (user must be champion as role)
2) go to "My Dojos" link
3) go to "Manage" under "Users" column

![screen shot 2016-04-07 at 00 29 08](https://cloud.githubusercontent.com/assets/1916339/14341824/6307f00a-fc6b-11e5-9427-54eed84053b6.png)

**Comment by Wardormeur** [comment]
Hard refresh your cache with ctrl+maj+r, we've been fixing an issue here this week

**Comment by elnomade** [comment]
Current only workaround is use Chrome with Incognito mode.
Keep it open until you fix it. A promise is not a fix.

**Comment by Wardormeur** [comment]
It's not a promise, it's a fact, there is nothing broken but your browser cache. Please refer to http://refreshyourcache.com/en/cache/ or https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.VwZsBnwoTMU for more details regarding plateform and browser.
Indeed, we need to work on deployment and versionning of the js files to avoid outdated cache, but that's not our priority right now.
