### ISSUE TITLE
All emails are sent in english

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/cp-zen-platform#852]
Even when there are templates for spanish in the crowdin project, all messages are sent in english instead of spanish.

Our Coderdojo is located in Córdoba, Argentina.

I couldn't find any option to set language preferences for our Coderdojo.

**Comment by Wardormeur** [comment]
I'll have a look at it today, I think it's missing in the deployment job

**Comment by Wardormeur** [comment]
Done :)
