### ISSUE TITLE
Missing spanish es_* translations in crowdin project

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/cp-zen-platform#853]
![captura de pantalla 2016-04-01 a las 1 00 39](https://cloud.githubusercontent.com/assets/1916339/14342781/af46a680-fc72-11e5-8be8-f624b7143dc6.png)
Even when it is possible to choose language_country options for each country in Latin America (e.g. Argentina, Chile, México), these translations are not available in the crowdin project.

We want to collaborate adding these translations but is not possible.

We need the zen platform project owner add these translations in crowdin.

**Comment by rosalanghammer** [comment]
Done by @PhilipHarney :)
