### ISSUE TITLE
White page of death, using firefox

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/cp-zen-platform#854]
User role: Champion
URL: https://zen.coderdojo.com/dashboard/dojo-list

Details:
After login, website redirects to dashboard and then it renders a white page.

Pastebin:
http://pastebin.com/RUrxURhC

How reproduce it:
1) login zen platform, using firefox

I tried using a private window and cleaning coderdojo cookies and history.
I tested Chrome and Safari and both worked fine at the same time I tried with Firefox.

**Comment by Wardormeur** [comment]
I did a deployment this morning, you mayhave loaded a page in the very small amount of time where the website is down ;)

**Comment by elnomade** [comment]
It happened several times, during different days, since March at least.

**Comment by elnomade** [comment]
Maybe it is a performance issue, not a deployment issue.

**Comment by Wardormeur** [comment]
We indeed have performance issue and are deeply looking into it atm. I'll close it but feel free to drop on our gitter (https://gitter.im/CoderDojo/community-platform) when this happen so we can have a real time inspection of it
