### ISSUE TITLE
Footer paragraph renders without translation

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/cp-zen-platform#857]
Crowdin paragraph renders without translation.
"You can correct any mistakes in the text on the websites using crowdin and make this website better."

Pastebin:
http://pastebin.com/azZ7MH7z

![screen shot 2016-04-08 at 00 42 30](https://cloud.githubusercontent.com/assets/1916339/14374111/30ac834c-fd28-11e5-9f6b-6aa9552c7da3.png)

**Comment by Wardormeur** [comment]
The key is not translated in crowdin
https://crowdin.com/translate/zen-community-platform/1/en-esar#3953

**Comment by elnomade** [comment]
Translation was also missing in es_ES strings. Latin American strings were created this week, only es_ES were available when the error was found
