### ISSUE TITLE
Event edition - Address textbox remains disabled

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/cp-zen-platform#858]
User role: Champion
URL: https://zen.coderdojo.com/dashboard/dojo/8308d14d-dda8-49a4-b217-6d07e9f88e2d/event-form/6e9900ca-b2f4-49eb-a4e3-5bc81c5c6740

Details:
dojo users list page is not rendering users data, only header

How reproduce it:
1) login zen platform (user must be champion as role)
2) go to "My Dojos" link
3) go to "Manage" under "Events" column
4) click "Edit" in any Event
5) Event Edition form loads. Even when it is possible to edit city, address textbox remains disabled.

![screen shot 2016-04-08 at 01 35 45](https://cloud.githubusercontent.com/assets/1916339/14374500/d30fbee8-fd2c-11e5-8f29-491e042f05e8.png)

**Comment by Wardormeur** [comment]
Hey elmonade
Try to hard refresh your cache as we've been adding the possibility to prefill the address box, which is not showing up

**Comment by Wardormeur** [comment]
Edit : issue validated, our bad :+1:

**Comment by Wardormeur** [comment]
Fixd !
